name: zhanghuan
description: "Tool for Tianjin ZHIC."
version: 1.0.4

environment:
  sdk: ^3.10.8

dependencies:
  change_package_name: ^1.1.0
  crypto: ^3.0.7
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.14.4
  fluttertoast: ^9.0.0
  html: ^0.15.6
  http: ^1.6.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/icon.png
  
  fonts:
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSans-Regular.ttf
          weight: 400

flutter_launcher_icons:
    android: true
    image_path: "assets/images/icon.png"
    adaptive_icon_background: "#ffffff"
    adaptive_icon_foreground: "assets/images/icon.png"